# Generated by Django 4.2.1 on 2023-06-05 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_investors_audiencelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupsOfficesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default=None, max_length=400)),
                ('startups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.startups')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorOfficesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default=None, max_length=400)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.investors')),
            ],
        ),
    ]
